### ISSUE TITLE
Changes not picked up when using watcher

### ISSUE THREAD

**Issue by gerwinbrunner** [RJHwang/rollup-plugin-css-porter#1]
It seems that changes to the css are not picked up when using the rollup-watcher plugin.
A complete rebuild works.

Any idea on how to fix this?

**Comment by rj-hwang** [comment]
Did you mean ''rollup -c -w" (https://github.com/rollup/rollup-watch)?

**Comment by rj-hwang** [comment]
I just checked it. Your problem is really existing if use with https://github.com/rollup/rollup-watch plugin.

**Comment by gerwinbrunner** [comment]
Any idea how to fix it?
Gerwin

**Comment by rj-hwang** [comment]
Fixed in [v0.1.2](https://github.com/RJHwang/rollup-plugin-css-porter/tree/0.1.2)
